### ISSUE TITLE
多机器微调

### ISSUE THREAD

**Issue by ftgreat** [WangRongsheng/Aurora#12]
请问多机器怎么做全参数微调。可以使用deepspeed这些并行框架吗，谢谢

**Comment by WangRongsheng** [comment]
您好，感谢您的关注，我们的工作基于[factory](https://github.com/hiyouga/LLaMA-Factory) 框架并进行了部分修改，如果您需要多机器参数微调等，可以查看相关工作（该工作支持deepspeed等并行策略）。
