### ISSUE TITLE
Mixtral-8x7B-Instruct-v0.1 generate结果和论文中不一致

### ISSUE THREAD

**Issue by hxdtest** [WangRongsheng/Aurora#13]
在本地使用vllm，相同的prompt，generate结果和论文中的不同。
`(Pdb) llm.generate("你是谁？", sampling_params)
[RequestOutput(request_id=7, prompt='你是谁？', prompt_token_ids=[1, 28705, 29383, 28971, 235, 179, 132, 29771], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='\n\n我是一个程序员，我喜欢折腾各种东西。`
论文中的generate结果：
`User
你是谁？
Mixtral-8x7B-Instruct-v0.1
Hello! I’m an assistant designed to help you with a variety of tasks. I strive to provide useful, honest, and
respectful responses while ensuring your data is secure. It’s nice to meet you! How can I assist you today?
你好，很高兴认识你！ 我可以wie kann ich Ihnen helfen heute？nitschen Sie mir bitte helfen?`

**Comment by WangRongsheng** [comment]
您好，我们使用了原始的加载方式进行推理。关于推理结果，由于采样方法和参数不同，会导致差异存在。其次，vllm的推理优化过程也可能会改变结果。
