### ISSUE TITLE
Possibility to open source DPO training data?

### ISSUE THREAD

**Issue by Morizeyao** [WangRongsheng/Aurora#14]
Hi, as title said, I'm interested in the data used in DPO training. Is it possible to get it?

**Comment by WangRongsheng** [comment]
Yes, you can download it from [here](https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM/blob/main/data/comparison_data_v2.json)

**Comment by Morizeyao** [comment]
I only see English DPO data in the link, do we have Chinese version?
Thanks in advance!

**Comment by WangRongsheng** [comment]
@Morizeyao Hi, you can download it that chinese version data. https://drive.google.com/file/d/1F4JzSGM_DdCuREdNRJD04IIZ8DVPI_7A/view?usp=drive_link

**Comment by Morizeyao** [comment]
I have submitted access request, can you pass it? xD
