### ISSUE TITLE
对论文中提到的训练数据的疑惑

### ISSUE THREAD

**Issue by XuJianzhi** [WangRongsheng/Aurora#15]
看您论文中第二部分 数据 中写到:
alpaca_data_zh_51k dataset consists of approximately 51000 sentence pairs, each containing a Chinese sentence and its corresponding English translation.

但我看到 https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/alpaca_data_zh_51k.json 中的数据情况是，大多数数据的instruction和output都是纯中文的，没有对应的英文。

是我找错地方了吗？？还是说您对链接中的数据，又做了翻译，再作为训练数据？

麻烦您回答，谢谢！

**Comment by WangRongsheng** [comment]
对于`alpaca_data`您可以通过以下方法获取：
1. En：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/data/alpaca_data_en_52k.json
2. Zh：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/alpaca_data_zh_51k.json

**Comment by XuJianzhi** [comment]
> 对于`alpaca_data`您可以通过以下方法获取：
> 
> 1. En：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/data/alpaca_data_en_52k.json
> 2. Zh：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/alpaca_data_zh_51k.json

您好，我不明白的点是，这个数据貌似并不是论文中说的“一句中文，对应相应的英文”。
即便是这两份数据，样本数都不一样，内容貌似也没有对应关系。

**Comment by XuJianzhi** [comment]
我后来搜到了确实有对应关系，所以我的问题变成了：
中英文的两个同义的样本，是如何组合的？
是把instruction=中文instruction+英文instruction，input、output同理？
还是这两个样本就是这两个样本？即中文5万条+英文5万条=10万条？？

**Comment by WangRongsheng** [comment]
> 我后来搜到了确实有对应关系，所以我的问题变成了： 中英文的两个同义的样本，是如何组合的？ 是把instruction=中文instruction+英文instruction，input、output同理？ 还是这两个样本就是这两个样本？即中文5万条+英文5万条=10万条？？

是两个样本：中文数据，英文数据。
