### ISSUE TITLE
有没有多gpu推理的脚本?一张3090刚好放不下

### ISSUE THREAD

**Issue by wonder-hy** [WangRongsheng/Aurora#16]
试了下用vllm多卡推理,没有成功...
在这试着问下
谢谢

**Comment by WangRongsheng** [comment]
嗨,

推荐您使用天宫云镜像一键部署使用：
- 镜像：https://www.xiangongyun.com/image/detail/bbcdc87e-20de-561c-a298-4323cf2f6fb2
- 视频教程：https://www.bilibili.com/video/BV1xw411E7To/

如果您需要在单机多卡上运行该模型，请下载[app.py](https://github.com/WangRongsheng/Aurora/blob/main/app.py)，并以：
```python
CUDA_VISIBLE_DEVICES=0,1,.. python app.py
```
