### ISSUE TITLE
How to merge lora weight with the base model?

### ISSUE THREAD

**Issue by noforit** [WangRongsheng/Aurora#17]
I want to use with the vllm, so how to  merge lora weight with the base model and save the whole model ? 
我想用vllm跑推理，怎么merge然后保存整个模型。

**Comment by WangRongsheng** [comment]
这可能对你有帮助：

```python
python src/export_model.py \
    --model_name_or_path ./Mixtral-8x7B-Instruct-v0.1 \
    --checkpoint_dir Aurora \
    --finetuning_type lora \
    --quantization_bit 4 \
    --template mistral \
    --output_dir export
```

**Comment by noforit** [comment]
谢谢，应该是--export_dir 吧， --output_dir 报错了

**Comment by noforit** [comment]
但是还是有问题
`[2024-02-02 19:13:04,385] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
02/02/2024 19:13:09 - INFO - llmtuner.model.loader - Quantizing model to 4 bit.
02/02/2024 19:13:37 - INFO - llmtuner.model.adapter - Fine-tuning method: LoRA
02/02/2024 19:13:37 - INFO - llmtuner.model.adapter - Loaded fine-tuned model from checkpoint(s): /data/home/syji/hf_model/wangrongsheng/Aurora-Plus/final-checkpoint
02/02/2024 19:13:37 - INFO - llmtuner.model.loader - trainable params: 0 || all params: 46706200576 || trainable%: 0.0000
02/02/2024 19:13:37 - INFO - llmtuner.model.loader - This IS expected that the trainable params is 0 if you are using model for inference only.
`
输出日志未报错
但是指定输出文件夹只有
![image](https://github.com/WangRongsheng/Aurora/assets/97608046/a367eb32-689c-4cae-b8d5-c36e889c983f)

**Comment by WangRongsheng** [comment]
I will check it, thank you
