### ISSUE TITLE
与Flash Attention 2结合

### ISSUE THREAD

**Issue by wangzi324** [WangRongsheng/Aurora#18]
如何让Aurora与Flash Attention 2结合，进一步加快推理速度

**Comment by WangRongsheng** [comment]
请在机器上安装flash attention，然后以https://github.com/WangRongsheng/Aurora?tab=readme-ov-file#3-inference 的方法运行即可使用

**Comment by wangzi324** [comment]
您好！之前的回复已收到！谢谢！


我想进一步问问，安装flash attention后，如何在Aurora代码中做适应性调整，以保证可以调用flash attention处理token。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangRongsheng/Aurora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WangRongsheng/Aurora] 与Flash Attention 2结合 (Issue #18)





 
请在机器上安装flash attention，然后以https://github.com/WangRongsheng/Aurora?tab=readme-ov-file#3-inference 的方法运行即可使用

**Comment by wangzi324** [comment]
您好！之前的回复已收到！谢谢！


我想进一步问问，安装flash attention后，如何在Aurora代码中做适应性调整，以保证可以调用flash attention处理token。


8x7B MoE与Flash Attention 2结合，不到10行代码实现快速推理 (qq.com)&nbsp;
这是我目前找到的Aurora与flash attention可能的结合方式，我更想进一步问问链接中的代码段应该加入到Aurora的哪个文件的什么位置呢？


谢谢！





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "WangRongsheng/Aurora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WangRongsheng/Aurora] 与Flash Attention 2结合 (Issue #18)





 
请在机器上安装flash attention，然后以https://github.com/WangRongsheng/Aurora?tab=readme-ov-file#3-inference 的方法运行即可使用

**Comment by wangzi324** [comment]
我成功安装了flash attention，调用模型的指令中补充了--flash_attn True，模型加载时出现了llmtuner.model.loader - Using FlashAttention-2 for faster training and inference. 

但是模型实际推理速度没有加快，这是为什么？
