### ISSUE TITLE
是否考虑上传模型到modelscope.cn

### ISSUE THREAD

**Issue by tshemeng** [WangRongsheng/Aurora#5]

**Comment by WangRongsheng** [comment]
是的，我们正在完成它。

**Comment by tshemeng** [comment]
谢谢，已经看到模型了

**Comment by WangRongsheng** [comment]
现在您可以通过ModelScope访问我们的模型了：https://modelscope.cn/models/wangrongsheng/Aurora-Mixtral-8x7B/summary
