### ISSUE TITLE
加载微调权重之后，提英文问题，默认也是用中文回答，是我参数没有配置对么？

### ISSUE THREAD

**Issue by fouvy** [WangRongsheng/Aurora#7]
RT

**Comment by WangRongsheng** [comment]
感谢您对项目的关注。Aurora旨在改善Mixtral-8x7b在中文对话中的潜在对话问题，前期训练并未混合入其它语料数据，后期我们将逐渐融合不同语言数据进行训练，以全面改善其能力。
