### ISSUE TITLE
what optimization strategy is used?

### ISSUE THREAD

**Issue by g-h-chen** [WangRongsheng/Aurora#8]
Hi Rongsheng, 
        Thanks for your work! I'm wondering what optimization strategy is used (ZERO-1/2/3)?

**Comment by g-h-chen** [comment]
Also, can you reveal how many GPU hours you used in your training?

**Comment by WangRongsheng** [comment]
> Hi Rongsheng, Thanks for your work! I'm wondering what optimization strategy is used (ZERO-1/2/3)?

@g-h-chen Hi, this is helpful for you. https://github.com/WangRongsheng/Aurora?tab=readme-ov-file#train

**Comment by WangRongsheng** [comment]
> Also, can you reveal how many GPU hours you used in your training?

We use a single NVIDIA H100. The traing time information is here. https://huggingface.co/wangrongsheng/Aurora/blob/main/train_results.json

**Comment by g-h-chen** [comment]
Thanks for your reply. I read the source code but found no sign of using any of the ZERO optimization. Is this the case? Did I miss anything?

**Comment by WangRongsheng** [comment]
> Thanks for your reply. I read the source code but found no sign of using any of the ZERO optimization. Is this the case? Did I miss anything?

we support Deepspeed Zero, but we don't use it. we will update readme and you can check it later.

**Comment by g-h-chen** [comment]
Roger that! Thanks!
