### ISSUE TITLE
中文lora降低了逻辑判断能力

### ISSUE THREAD

**Issue by ningpengtao-coder** [WangRongsheng/Aurora#9]
model mixtral 7x8 + chinese lora 4 bit quantization
提示
1.you have a question.think step by step.if the question talk about china's topic then output {\"topic\":\"china\"} else output {\"topic\":\"other\"}.Question:浙江在哪里？

2.你有一个问题，一步步思考。如果问题涉及中国的主题，则输出 {\"topic\":\"china\"} else 输出 {\"topic\":\"other\"}.Question:浙江在哪里？

mixtral:
能够推理过程并描述。
output: The question is about a location in China, so the topic is related to China.\nAnswer: {\"topic\": \"china\"}\n\nNote: Zhejiang is a province located in the eastern part of China, near Shanghai and bordering the East China Sea.

chinese lora:
没有推理和描述。
output: {\"topic\":\"other\"}.

看起来，lora版本遗忘了推理相关的知识导致逻辑判断推理（是不是训练数据中缺少中英文对齐、COT、STEM相关的数据？）。

我非常喜欢mixtral 7bx8，模型性能很强但是中文比较差，希望你越做越好。

**Comment by WangRongsheng** [comment]
感谢您的反馈，我们也发现了Aurora在推理上被减弱了CoT的能力，但在原始模型中却存在一步一步推理的能力。我们认为可以使用DPO/PPO改善这样的问题，后续我们会发布相关的模型，请您多多关注~（另外您可以加载checkpoints的时候选择低轮次的进行尝试，这可以部分缓解Mixtral能力的丢失）。

**Comment by ningpengtao-coder** [comment]
@WangRongsheng 你看一下，https://github.com/TencentARC/LLaMA-Pro能不能改进COT问题（这个项目解决了灾难性遗忘问题）。

**Comment by WangRongsheng** [comment]
@ningpengtao-coder thanks, i will check it.

**Comment by WangRongsheng** [comment]
Please check dpo model:
```txt
User: 你有一个问题，一步步思考。如果问题涉及中国的主题，则输出 {"topic":"china"} else 输出 {"topic":"other"}.Question:浙江在哪里？
Assistant: {"topic":"china"}

User: 你有一个问题，请给出你一步步思考的过程。如果问题涉及中国的主题，则输出 {"topic":"china"} else 输出 {"topic":"other"}.Question:浙江在哪里？
Assistant: 当我收到这个问题时，我的第一步是确定它是否涉及中国的主题。在这种情况下，浙江是中国的一省，因此我将输出 {"topic":"china"}。浙江是中国的一个沿海省，位于东北部，由江西、安徽、江苏和福建四个省分隔开。它拥有广阔的沿海地带，因此它是中
  的重要的经济中心。因此，我的最终回答是 {"topic":"china"}。
```

**Comment by WangRongsheng** [comment]
@ningpengtao-coder Please check it. https://github.com/WangRongsheng/Aurora/tree/dpo

**Comment by ningpengtao-coder** [comment]
@WangRongsheng 我使用的4位量化版本性能下降比较多，所以没有完全复现，但是目前遵循中文提示的能力提升了不少。

你有一个问题，一步步思考。如果问题涉及中国的主题，则输出 {\"topic\":\"china\"} else 输出 {\"topic\":\"other\"}.Question:浙江在哪里？

{\"topic\":\"other\"} 因为这个问题涉及地理位置而不是中国特定的主题。

你有一个问题，请给出你一步步思考的过程。如果问题涉及中国的主题，则输出 {\"topic\":\"china\"} else 输出 {\"topic\":\"other\"}.Question:浙江在哪里？

这是我的思考过程：\n\n1. 首先，我们需要确定地球上的地区或国家被指称为“浙江”。\n2. 浙江是中国东南部的一个省，因此这是一个涉及中国的问题。\n\n因此，输出为 {\"topic\":\"china\"}。
